export type Language = "ar" | "en";
export const english: Record<string, string> = {
"نسيت كلمة المرور؟": "Forgot password?",
"استرجاع كلمة المرور عبر البريد غير متاح حالياً. تواصل مع مسؤول الموقع.": "Email recovery is currently unavailable. Contact the site administrator.",
"استرجاع كلمة المرور عبر البريد غير مهيّأ بعد.": "Email password recovery is not configured yet.",
"تعذّر إرسال البريد. حاول لاحقاً أو تواصل مع مسؤول الموقع.": "Unable to send email. Try later or contact the site administrator.",
"انتظر دقيقة قبل طلب كود جديد.": "Wait a minute before requesting another code.",
"الكود غير صحيح أو انتهت صلاحيته. اطلب كوداً جديداً.": "The code is invalid or expired. Request a new code.",
"كلمة المرور يجب أن تكون من 12 إلى 128 محرفاً وأن تتطابق مع التأكيد.": "Use 12–128 characters and make sure the passwords match.",
"تغيّرت كلمة المرور. أعد تسجيل الدخول.": "The password changed. Sign in again.",
"كلمة المرور الجديدة": "New password",
"تأكيد كلمة المرور": "Confirm password",
"استخدم كلمة مرور من 12 محرفاً على الأقل.": "Use a password of at least 12 characters.",
"تم تغيير كلمة المرور. سجّل الدخول بالكلمة الجديدة.": "Password changed. Sign in with your new password.",
"سنرسل كود تحقق إلى بريد المدير المعتمد فقط.": "A verification code will be sent only to the approved manager email.",
"تم إرسال الكود. صلاحيته 10 دقائق، ولمرة واحدة.": "Code sent. It is valid for 10 minutes and one use only.",
"كود التحقق": "Verification code",
"تعيين كلمة المرور الجديدة": "Set new password",
"إرسال كود جديد": "Send a new code",
"جارٍ إرسال الكود…": "Sending code…",
"إرسال كود التحقق": "Send verification code",
"تغيير كلمة المرور يسجّل خروجك. لديك تغييرات غير محفوظة. هل تريد المتابعة؟": "Changing your password signs you out. You have unsaved changes. Continue?",
"تغيير كلمة المرور": "Change password",
"بعد التغيير، تنتهي الجلسات القديمة وستسجّل الدخول مجدداً.": "Changing your password ends old sessions. You will need to sign in again.",
"كلمة المرور الحالية": "Current password",
"حفظ كلمة المرور": "Save password",
  "الرئيسية": "Home", "نبذة": "About", "المشاريع": "Ventures", "المقالات": "Articles", "الإعلام": "Media", "التواصل": "Contact", "إعدادات الموقع": "Site settings",
  "التعريف": "Eyebrow", "الاسم والعنوان": "Name and title", "العنوان الفرعي": "Subtitle", "الوصف": "Description", "نص زر الاستكشاف": "Explore button text", "صورة الغلاف": "Cover image", "عنوان قسم الإبداعات": "Creations section label", "عنوان الرؤية": "Vision heading", "أبعاد الإبداع": "Creative dimensions", "الرمز": "Symbol", "التصنيف": "Category", "العنوان": "Title", "رابط الصفحة": "Page link", "عنوان المسيرة": "Journey label", "عنوان القسم": "Section heading", "الإحصائيات": "Statistics", "القيمة": "Value", "المسيرة": "Journey", "الفترة": "Period", "ملاحظة أسفل المشاريع": "Note below ventures", "الاسم": "Name", "صورة المشروع": "Venture image", "رابط الموقع (اختياري)": "Website link (optional)", "التاريخ": "Date", "نص المقال": "Article body", "عنوان الجهات الإعلامية": "Publications heading", "الجهات الإعلامية": "Publications", "البريد الإلكتروني": "Email", "الهاتف": "Phone", "الموقع": "Location", "اسم الموقع": "Site name", "وصف محركات البحث": "SEO description", "رابط الموقع": "Site URL", "صورة المشاركة": "Social sharing image", "نص حقوق الملكية": "Copyright text",
  "مأمون العتيبي": "MA’AMOUN AL OTAIBI", "استوديو المحتوى": "CONTENT STUDIO", "إدارة المحتوى": "Content management", "مساحة العمل": "Workspace", "أقسام إدارة المحتوى": "Content sections", "مكتبة الصور": "Image library", "زيارة الموقع ↗": "Visit website ↗", "تسجيل الخروج": "Sign out", "تغييرات غير محفوظة": "Unsaved changes", "المسودة محفوظة": "Draft saved", "صفحات الموقع": "Website pages", "عناصر المحتوى": "Content entries", "آخر نشر": "Last published", "المحتوى الأصلي": "Original content", "لم يُحفظ بعد": "Not saved yet", "صورك، في مكان واحد": "Your images, in one place", "اصنع النسخة القادمة": "Create the next version", "ارفع صورة ثم اخترها داخل أي صفحة. JPG، PNG، WebP، GIF — حتى 5 MB.": "Upload an image and use it on any page. JPG, PNG, WebP, GIF — up to 5 MB.", "آخر حفظ:": "Last saved:", "التعديلات لا تظهر للزوار حتى نشرها.": "Changes appear on the website after publishing.", "معاينة ↗": "Preview ↗", "جارٍ العمل…": "Working…", "حفظ المسودة": "Save draft", "نشر التغييرات ←": "Publish changes →", "اختر صورة لإضافتها إلى الصفحة": "Choose an image for this page", "مكتبة الوسائط": "Media library", "الصور المرفوعة تُحفظ على السيرفر وتبقى متاحة بعد إعادة التشغيل.": "Uploaded images are stored on the server and remain available after restarting.", "جارٍ الرفع…": "Uploading…", "＋ رفع صورة": "＋ Upload image", "استخدام الصورة": "Use image", "نسخ المسار": "Copy path", "محتوى الصفحة": "Page content", "حرّر النصوص والصور مع الحفاظ على تصميم الموقع.": "Edit text and images while keeping the website design.", "أضف العناصر، رتّبها، أو احذف ما لم تعد تحتاجه.": "Add, reorder, or remove entries.", "＋ إضافة عنصر": "＋ Add entry", "لا توجد عناصر بعد. ابدأ بإضافة أول عنصر.": "No entries yet. Add your first entry.", "عنصر": "Entry", "نقل للأعلى": "Move up", "نقل للأسفل": "Move down", "حذف": "Delete", "بدون صورة": "No image", "اختيار من مكتبة الصور": "Choose from image library", "المسودات محفوظة بشكل مستقل عن الموقع المنشور": "Drafts are saved separately from the published website",
  "تم اختيار الصورة. احفظ المسودة ثم انشر لإظهارها للزوار.": "Image selected. Save the draft and publish to show it on the website.", "لديك تغييرات غير محفوظة. هل تريد تسجيل الخروج؟": "You have unsaved changes. Sign out anyway?", "احفظ المسودة قبل فتح المعاينة.": "Save the draft before previewing.", "تم حفظ المسودة. النسخة المنشورة لم تتغير.": "Draft saved. The published website is unchanged.", "نشر المسودة الحالية على الموقع للزوار؟": "Publish this draft to the website?", "تم النشر. المحتوى الجديد ظاهر الآن على الموقع.": "Published. The new content is now live.", "حجم الصورة الأقصى 5 MB.": "The maximum image size is 5 MB.", "تم رفع الصورة بنجاح.": "Image uploaded successfully.", "تم نسخ مسار الصورة.": "Image path copied.", "حذف هذا العنصر من المسودة؟": "Delete this entry from the draft?", "تعذّر الاتصال بالسيرفر.": "Unable to connect to the server.", "تعذر الاتصال بالسيرفر.": "Unable to connect to the server.", "تعذّر إكمال الطلب.": "Unable to complete the request.",
  "مساحة إدارة المحتوى": "Content management studio", "الكلمات، المشاريع، والأفكار.": "Words, ventures, and ideas.", "كل تفاصيل الموقع من مكان واحد.": "Every website detail, in one place.", "كلمة المرور": "Password", "جارٍ تسجيل الدخول…": "Signing in…", "الدخول إلى لوحة التحكم ←": "Open dashboard →", "لوحة التحكم بحاجة إلى إعداد بيانات الدخول على السيرفر. راجع ملف CMS.md لتعيين كلمة المرور وسر الجلسة.": "Configure server credentials first. See CMS.md to set the password and session secret.", "العودة إلى الموقع ↗": "Back to website ↗",
  "اللغة": "Language", "العربية": "Arabic", "الإنكليزية": "English", "المظهر": "Appearance", "فاتح": "Light", "داكن": "Dark",
  "معاينة المسودة — الزوار يشاهدون النسخة المنشورة.": "Draft preview — visitors see the published version.", "العودة إلى لوحة التحكم": "Back to dashboard",
  "مصدر الطلب غير مسموح.": "This request origin is not allowed.", "سجّل الدخول للمتابعة.": "Sign in to continue.", "حجم الطلب يتجاوز الحد المسموح.": "The request exceeds the size limit.", "طلب غير صالح.": "Invalid request.", "تعذّر إكمال الطلب. تحقق من إعدادات التخزين وحاول مجدداً.": "Unable to complete the request. Check storage settings and try again.", "محاولات كثيرة. حاول بعد 15 دقيقة.": "Too many attempts. Try again in 15 minutes.", "كلمة المرور غير صحيحة.": "Incorrect password.", "اضبط CMS_ADMIN_PASSWORD (12 محرفاً على الأقل) وCMS_SESSION_SECRET (32 محرفاً على الأقل) في إعدادات السيرفر.": "Set CMS_ADMIN_PASSWORD (at least 12 characters) and CMS_SESSION_SECRET (at least 32 characters) on the server.", "تسجيل الدخول غير مهيّأ. اضبط كلمة المرور وسر الجلسة في إعدادات السيرفر.": "Sign-in is not configured. Set the server password and session secret.", "نسخة غير صالحة.": "Invalid revision.", "احفظ المسودة أولاً.": "Save the draft first.", "محتوى غير صالح.": "Invalid content.", "صفحات المحتوى غير مكتملة.": "Content pages are incomplete.", "بيانات الصفحة غير مكتملة.": "Page data is incomplete.", "حقول الصفحة غير صالحة.": "Invalid page fields.", "نص غير صالح أو أطول من الحد المسموح.": "Invalid text or text exceeds the length limit.", "استخدم رابطاً صالحاً أو مسار صورة محلياً.": "Use a valid link or local image path.", "رابط الموقع يجب أن يكون رابط HTTP أو HTTPS كاملاً.": "The site URL must be a complete HTTP or HTTPS URL.", "الحد الأقصى 100 عنصر لكل قائمة.": "Each list can contain up to 100 entries.", "معرّف عنصر غير صالح أو مكرر.": "Invalid or duplicate entry ID.", "حقول العنصر غير صالحة.": "Invalid entry fields.", "تم تعديل المسودة من جلسة أخرى. أعد تحميل المحتوى قبل الحفظ.": "Another session changed this draft. Reload the content before saving.", "طلب رفع صورة غير صالح.": "Invalid image upload request.", "اختر صورة حتى 5 MB.": "Choose an image up to 5 MB.", "الصور المدعومة: JPG وPNG وWebP وGIF.": "Supported images: JPG, PNG, WebP, and GIF.", "قاعدة بيانات CMS غير متاحة. يجب ربط DB.": "CMS database unavailable. Configure the DB binding.", "تخزين الصور غير متاح. يجب ربط MEDIA.": "Image storage unavailable. Configure the MEDIA binding.",
};
const arabic = Object.fromEntries(Object.entries(english).map(([ar, en]) => [en, ar]));
export function translate(text: string, language: Language): string {
  return language === "en" ? english[text] ?? text : arabic[text] ?? text;
}
export function translateError(text: string, language: Language): string {
  if (!text) return "";
  return translate(english[text] || arabic[text] ? text : "تعذّر إكمال الطلب.", language);
}
